-- Supabase schema for Go Game Pro
-- Run this in the Supabase SQL editor.

create table if not exists game.waiting_room (
  user_id uuid primary key references auth.users(id) on delete cascade,
  nickname text,
  created_at timestamptz not null default now()
);

create table if not exists game.game_sessions (
  id uuid primary key default gen_random_uuid(),
  black_id uuid not null references auth.users(id) on delete cascade,
  white_id uuid not null references auth.users(id) on delete cascade,
  board_state jsonb not null default '[]'::jsonb,
  next_turn text not null default 'black',
  black_captures integer not null default 0,
  white_captures integer not null default 0,
  moves jsonb not null default '[]'::jsonb,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists game.moves (
  id bigint generated by default as identity primary key,
  session_id uuid not null references game.game_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  x integer not null check (x between 0 and 18),
  y integer not null check (y between 0 and 18),
  player text not null check (player in ('black', 'white')),
  turn_number integer not null,
  created_at timestamptz not null default now()
);

create or replace function game.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_game_sessions on game.game_sessions;
create trigger trg_touch_game_sessions
before update on game.game_sessions
for each row execute function game.touch_updated_at();

alter table game.waiting_room enable row level security;
alter table game.game_sessions enable row level security;
alter table game.moves enable row level security;

-- Minimal policies; adjust for your security model as needed.
drop policy if exists "waiting room read own" on game.waiting_room;
drop policy if exists "waiting room write own" on game.waiting_room;
drop policy if exists "game sessions read participants" on game.game_sessions;
drop policy if exists "game sessions write participants" on game.game_sessions;

create policy "waiting room read own"
on game.waiting_room
for select
using (auth.uid() = user_id);

create policy "waiting room write own"
on game.waiting_room
for insert
with check (auth.uid() = user_id);

create policy "game sessions read participants"
on game.game_sessions
for select
using (auth.uid() = black_id or auth.uid() = white_id);

create policy "game sessions write participants"
on game.game_sessions
for update
using (auth.uid() = black_id or auth.uid() = white_id)
with check (auth.uid() = black_id or auth.uid() = white_id);

create policy "game sessions insert authenticated"
on game.game_sessions
for insert
with check (auth.role() = 'authenticated');

create policy "moves read participants"
on game.moves
for select
using (
  exists (
    select 1 from game.game_sessions gs
    where gs.id = session_id
      and (auth.uid() = gs.black_id or auth.uid() = gs.white_id)
  )
);

create policy "moves insert participants"
on game.moves
for insert
with check (
  auth.uid() = user_id and exists (
    select 1 from game.game_sessions gs
    where gs.id = session_id
      and (auth.uid() = gs.black_id or auth.uid() = gs.white_id)
  )
);

-- ============================================================
-- RPC: 查询玩家个人信息（昵称 + 段位）
-- 从 auth.users 的 raw_user_meta_data 中读取
-- ============================================================
create or replace function public.get_player_profile(player_id uuid)
returns table (
  user_id uuid,
  nickname text,
  rank text
)
language sql
security definer
set search_path = ''
as $$
  select 
    id as user_id,
    coalesce(raw_user_meta_data->>'nickname', '棋手') as nickname,
    coalesce(raw_user_meta_data->>'rank', '业余1段') as rank
  from auth.users
  where id = player_id;
$$;
